const token=localStorage.getItem('jua_token'),$=s=>document.querySelector(s);let members=[],questions=[];
const api=async(p,o={})=>{const r=await fetch(p,{...o,headers:{'content-type':'application/json',authorization:`Bearer ${token}`}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d};
const money=n=>`KES ${Number(n).toLocaleString()}`,date=v=>new Date(v).toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'}),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function showMembers(){const q=$('#memberSearch').value.toLowerCase();$('#memberRows').innerHTML=members.filter(m=>`${m.displayName} ${m.phone}`.toLowerCase().includes(q)).map(m=>`<tr><td>${esc(m.displayName)}${m.role==='admin'?' <small>(admin)</small>':''}</td><td>${esc(m.phone)}</td><td>${money(m.walletBalance)}</td><td>${date(m.createdAt)}</td></tr>`).join('')||'<tr><td colspan="4">No matching members.</td></tr>'}
function showQuestions(){const q=$('#questionSearch').value.toLowerCase();$('#questionRows').innerHTML=questions.filter(x=>`${x.prompt} ${x.category}`.toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.prompt)}</td><td>${esc(x.category)}</td><td>${esc(x.options[x.answer_index])}</td><td><span class="status ${x.active?'paid':'rejected'}">${x.active?'active':'paused'}</span></td><td><button data-question="${x.id}" data-active="${x.active}">${x.active?'Pause':'Activate'}</button></td></tr>`).join('')||'<tr><td colspan="5">No matching questions.</td></tr>';document.querySelectorAll('[data-question]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/questions/${b.dataset.question}`,{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});await loadQuestions()}catch(e){alert(e.message)}})}
async function loadQuestions(){questions=(await api('/api/admin/questions')).questions;showQuestions()}
async function loadWithdrawals(){const rows=(await api('/api/admin/withdrawals')).withdrawals;$('#withdrawalRows').innerHTML=rows.map(w=>`<tr><td>${esc(w.display_name)}</td><td>${esc(w.phone)}</td><td>${money(w.amount)}</td><td>${esc(w.reference)}</td><td><span class="status ${esc(w.status)}">${esc(w.status)}</span></td><td>${w.status==='pending'?`<button data-withdrawal="${w.id}" data-status="processing">Start</button>`:w.status==='processing'?`<button data-withdrawal="${w.id}" data-status="paid">Mark paid</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6">No withdrawal requests.</td></tr>';document.querySelectorAll('[data-withdrawal]').forEach(b=>b.onclick=async()=>{try{await api(`/api/admin/withdrawals/${b.dataset.withdrawal}`,{method:'PATCH',body:JSON.stringify({status:b.dataset.status})});await loadWithdrawals();await loadOverview()}catch(e){alert(e.message)}})}
async function loadOverview(){const d=await api('/api/admin/overview');$('#memberCount').textContent=d.members;$('#questionCount').textContent=d.questions;$('#walletTotal').textContent=money(d.walletBalance);$('#withdrawalCount').textContent=d.pendingWithdrawals}
async function boot(){if(!token())return;try{const me=(await api('/api/me')).user;if(me.role!=='admin')return;$('#blocked').hidden=true;$('#dashboard').hidden=false;[members]=await Promise.all([api('/api/admin/members').then(x=>x.members),loadOverview(),loadQuestions(),loadWithdrawals()]);showMembers()}catch(e){console.error(e)}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));['members','withdrawals','questions','add'].forEach(id=>$('#'+id).hidden=id!==b.dataset.tab)});$('#memberSearch').oninput=showMembers;$('#questionSearch').oninput=showQuestions;
$('#questionForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/questions',{method:'POST',body:JSON.stringify({prompt:$('#prompt').value,category:$('#category').value,options:[...document.querySelectorAll('.option')].map(x=>x.value),answerIndex:Number($('#answerIndex').value)})});e.target.reset();$('#formError').textContent='Question added to the active bank.';await loadQuestions();await loadOverview()}catch(x){$('#formError').textContent=x.message}};$('#signOut').onclick=()=>{localStorage.removeItem('jua_token');location.href='/'};boot();
