const pageStyle=document.createElement('style');pageStyle.textContent=".skyline{height:245px;background-image:linear-gradient(0deg,rgba(5,19,34,.28),rgba(5,19,34,.04)),url('/nairobi-kenya.png');background-size:cover;background-position:center}.skyline:after,.skyline span,.skyline small{display:none}body:has(#landing:not([hidden])) .app-shell{padding-bottom:0}";document.head.append(pageStyle);
let authMode='register',game,answerIndex=0,answers=[];const $=s=>document.querySelector(s),token=()=>localStorage.getItem('jua_token'),money=n=>`KES ${Number(n).toLocaleString()}`;
const api=async(p,o={})=>{const r=await fetch(p,{...o,headers:{'content-type':'application/json',...(token()?{authorization:`Bearer ${token()}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Please try again.');return d};
const open=id=> $(`#${id}`).showModal(),close=id=>$(`#${id}`).close();function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function member(u){$('#landing').hidden=true;$('#member').hidden=false;$('#bottomNav').hidden=false;$('#bottomNav').style.display='flex';$('#memberName').textContent=u.displayName.toUpperCase();$('#walletBalance').textContent=money(u.walletBalance);$('#depositPhone').value=u.phone.replace(/^254/,'0');$('#withdrawPhone').value=u.phone.replace(/^254/,'0')}
async function restore(){$('#bottomNav').style.display='none';if(!token())return;try{member((await api('/api/me')).user)}catch{localStorage.removeItem('jua_token')}}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(b.dataset.open));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('chosen',x===b));$('#authTitle').textContent=authMode==='register'?'Create your account.':'Welcome back.';$('#authSubmit').innerHTML=(authMode==='register'?'Create account':'Sign in')+' <span>→</span>';$('#nameLabel').hidden=authMode==='login';$('#termsCheck').hidden=authMode==='login'});
$('#authForm').onsubmit=async e=>{e.preventDefault();try{const d=await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify({name:$('#name').value,phone:$('#phone').value,password:$('#password').value,acceptedTerms:$('#acceptedTerms').checked})});localStorage.setItem('jua_token',d.token);close('auth');member(d.user);toast('Karibu JUA! Your account is ready.')}catch(x){$('#authError').textContent=x.message}};
$('#depositButton').onclick=()=>open('deposit');$('#navDeposit').onclick=()=>open('deposit');$('#navWithdraw').onclick=()=>open('withdraw');
$('#depositForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/deposits',{method:'POST',body:JSON.stringify({amount:$('#depositAmount').value,phone:$('#depositPhone').value})});close('deposit');toast(d.message);const i=setInterval(async()=>{try{const s=await api(`/api/deposits/${d.id}`);if(s.status==='confirmed'){clearInterval(i);member((await api('/api/me')).user);toast(`${money(s.amount)} is now in your JUA wallet.`)}}catch{}},5000);setTimeout(()=>clearInterval(i),120000)}catch(x){$('#depositError').textContent=x.message}};
$('#withdrawForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/withdrawals',{method:'POST',body:JSON.stringify({amount:$('#withdrawAmount').value,phone:$('#withdrawPhone').value})});close('withdraw');toast(d.message)}catch(x){$('#withdrawError').textContent=x.message}};
async function start(){try{game=await api('/api/games',{method:'POST',body:JSON.stringify({stake:50})});answers=[];answerIndex=0;showQuestion();open('game')}catch(x){toast(x.message)}}function showQuestion(){const q=game.questions[answerIndex];$('#gameCategory').textContent=q.category.toUpperCase();$('#gamePrompt').textContent=q.prompt;$('#gameProgress').textContent=`Question ${answerIndex+1} of ${game.questions.length}`;$('#gameOptions').innerHTML=q.options.map((o,i)=>`<button data-answer="${i}"><b>${'ABCD'[i]}</b>${o}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>pick(Number(b.dataset.answer)))}
async function pick(a){answers.push(a);answerIndex++;if(answerIndex<game.questions.length)return showQuestion();try{const r=await api(`/api/games/${game.game.id}/submit`,{method:'POST',body:JSON.stringify({answers})});close('game');$('#resultTitle').textContent=r.result==='win'?'You take the round!':r.result==='draw'?'It is a draw.':'A close one.';$('#resultText').textContent=`You scored ${r.score}/${game.questions.length}. ${r.opponentName} scored ${r.opponentScore}/${game.questions.length}.`;open('result');member((await api('/api/me')).user)}catch(x){toast(x.message)}}
$('#playButton').onclick=start;document.querySelectorAll('.game-tile').forEach(b=>b.onclick=start);$('#signOut').onclick=()=>{localStorage.removeItem('jua_token');$('#member').hidden=true;$('#bottomNav').hidden=true;$('#bottomNav').style.display='none';$('#landing').hidden=false;toast('Signed out.')};restore();
