const pageStyle=document.createElement('style');pageStyle.textContent=".skyline{height:245px;background-image:linear-gradient(0deg,rgba(5,19,34,.28),rgba(5,19,34,.04)),url('/nairobi-kenya.png');background-size:cover;background-position:center}.skyline:after,.skyline span,.skyline small{display:none}body:has(#landing:not([hidden])) .app-shell{padding-bottom:0}.kenya-band{margin:23px 20px 0;padding:12px 14px;border-radius:13px;background:linear-gradient(90deg,#111 0 28%,#d5232b 28% 55%,#167549 55%);color:#fff;font:700 10px 'DM Mono';letter-spacing:1px}.profile-summary{background:#eef6f1;border:1px solid #c8dfd3;padding:12px;border-radius:10px;margin:14px 0;font-size:12px}.profile-summary b{display:block;font:700 22px 'Space Grotesk';margin-top:3px}.profile-note{font-size:10px;color:#667784;text-align:center}@media(min-width:760px){body{padding:28px}.app-shell{max-width:1100px;border-radius:26px;overflow:hidden}.landing{display:grid;grid-template-columns:1.05fr .95fr;gap:0 44px;align-items:center;padding:34px 52px}.landing .topbar,.landing .flag-band,.landing footer{grid-column:1/-1}.landing .skyline{grid-column:2;grid-row:2/4;margin:0;height:430px;border-radius:20px}.landing .heritage-grid{grid-column:1;margin:12px 0}.landing-copy{grid-column:1}.member-hero{padding:32px 54px}.challenge-card{margin:-17px 54px 0}.wallet-strip,.made-here{margin-left:54px;margin-right:54px}.section-block{padding-left:54px;padding-right:54px}.game-tile{min-height:170px}.member-footer{padding-bottom:90px}}";document.head.append(pageStyle);
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="/responsive.css">');document.body.insertAdjacentHTML('beforeend','<dialog id="profile" class="dialog"><form id="profileForm" class="modal-card"><button class="close-button" type="button" data-close="profile">×</button><p class="eyebrow">MY PROFILE</p><h2>Your JUA details.</h2><div class="profile-summary"><small>AVAILABLE BALANCE</small><b id="profileBalance">KES 0</b></div><label>Full name<input id="profileName" required maxlength="40"></label><label>Nickname<input id="profileNickname" maxlength="30" placeholder="What should players call you?"></label><label>Login phone number<input id="profilePhone" inputmode="tel" required></label><label>Preferred wallet number<input id="profileWalletPhone" inputmode="tel" required></label><p class="profile-note">Your wallet number is used for deposit prompts and withdrawal requests.</p><p class="form-error" id="profileError"></p><button class="primary-button">Save profile <span>→</span></button></form></dialog>');
let authMode='register',game,answerIndex=0,answers=[],currentUser=null;const $=s=>document.querySelector(s),token=()=>localStorage.getItem('jua_token'),money=n=>`KES ${Number(n).toLocaleString()}`;
const api=async(p,o={})=>{const r=await fetch(p,{...o,headers:{'content-type':'application/json',...(token()?{authorization:`Bearer ${token()}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Please try again.');return d};
const open=id=> $(`#${id}`).showModal(),close=id=>$(`#${id}`).close();function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function member(u){currentUser=u;$('#landing').hidden=true;$('#member').hidden=false;$('#bottomNav').hidden=false;$('#bottomNav').style.display='flex';$('#memberName').textContent=(u.nickname||u.displayName).toUpperCase();$('#walletBalance').textContent=money(u.walletBalance);document.querySelector('.wallet-strip span').textContent='AVAILABLE BALANCE';$('#depositPhone').value=(u.walletPhone||u.phone).replace(/^254/,'0');$('#withdrawPhone').value=(u.walletPhone||u.phone).replace(/^254/,'0');$('#profileName').value=u.displayName;$('#profileNickname').value=u.nickname||'';$('#profilePhone').value=u.phone.replace(/^254/,'0');$('#profileWalletPhone').value=(u.walletPhone||u.phone).replace(/^254/,'0');$('#profileBalance').textContent=money(u.walletBalance)}
async function restore(){$('#bottomNav').style.display='none';if(!token())return;try{member((await api('/api/me')).user)}catch{localStorage.removeItem('jua_token')}}
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(b.dataset.open==='auth'){const mode=/sign in/i.test(b.textContent)?'login':'register';document.querySelector(`[data-mode="${mode}"]`).click()}open(b.dataset.open)});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{authMode=b.dataset.mode;const signingIn=authMode==='login';document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('chosen',x===b));$('#authTitle').textContent=signingIn?'Welcome back.':'Create your account.';$('#authSubmit').innerHTML=(signingIn?'Sign in':'Create account')+' <span>→</span>';$('#nameLabel').hidden=signingIn;$('#name').disabled=signingIn;$('#termsCheck').hidden=signingIn;$('#acceptedTerms').disabled=signingIn});
$('#authForm').onsubmit=async e=>{e.preventDefault();try{const d=await api(`/api/auth/${authMode}`,{method:'POST',body:JSON.stringify({name:$('#name').value,phone:$('#phone').value,password:$('#password').value,acceptedTerms:$('#acceptedTerms').checked})});localStorage.setItem('jua_token',d.token);close('auth');member(d.user);toast('Karibu JUA! Your account is ready.')}catch(x){$('#authError').textContent=x.message}};
$('#profileButton').onclick=()=>open('profile');$('#profileForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/profile',{method:'PATCH',body:JSON.stringify({name:$('#profileName').value,nickname:$('#profileNickname').value,phone:$('#profilePhone').value,walletPhone:$('#profileWalletPhone').value})});close('profile');member(d.user);toast('Your profile has been saved.')}catch(x){$('#profileError').textContent=x.message}};
$('#withdrawAmount').min=500;$('#withdrawAmount').value=500;document.querySelector('#depositForm .modal-copy').textContent='Minimum deposit KES 200. Enter the mobile number that should receive the secure payment prompt.';document.querySelector('#withdraw h2').insertAdjacentHTML('afterend','<p class="modal-copy">Minimum withdrawal KES 500.</p>');document.querySelector('.member-hero').insertAdjacentHTML('afterend','<section class="wildlife-card" aria-label="Kenyan wildlife"><img src="https://acaciasafari.co.ug/wp-content/uploads/2021/10/Big-5-945x675.jpg" alt="African lion, elephant, buffalo, rhinoceros and leopard on the savannah"><div><p class="eyebrow">KENYAN WILDLIFE</p><h2>Wild, proud, unmistakably home.</h2></div></section>');
const roundEndsAt=Date.now()+1122000;const roundCountdown=document.querySelector('.challenge-topline span:last-child');function updateRoundTimer(){const left=Math.max(0,roundEndsAt-Date.now()),minutes=Math.floor(left/60000),seconds=Math.floor(left/1000)%60;roundCountdown.textContent=left?`Closes in ${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`:'Round closed'}updateRoundTimer();setInterval(updateRoundTimer,1000);
$('#depositButton').onclick=()=>open('deposit');$('#navDeposit').onclick=()=>open('deposit');$('#navWithdraw').onclick=()=>open('withdraw');
$('#depositForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/deposits',{method:'POST',body:JSON.stringify({amount:$('#depositAmount').value,phone:$('#depositPhone').value})});close('deposit');toast(d.message);const i=setInterval(async()=>{try{const s=await api(`/api/deposits/${d.id}`);if(s.status==='confirmed'){clearInterval(i);member((await api('/api/me')).user);toast(`${money(s.amount)} is now in your JUA wallet.`)}}catch{}},5000);setTimeout(()=>clearInterval(i),120000)}catch(x){$('#depositError').textContent=x.message}};
$('#withdrawForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/withdrawals',{method:'POST',body:JSON.stringify({amount:$('#withdrawAmount').value,phone:$('#withdrawPhone').value})});close('withdraw');toast(d.message)}catch(x){$('#withdrawError').textContent=x.message}};
async function start(){try{game=await api('/api/games',{method:'POST',body:JSON.stringify({stake:50})});answers=[];answerIndex=0;showQuestion();open('game')}catch(x){toast(x.message)}}function showQuestion(){const q=game.questions[answerIndex];$('#gameCategory').textContent=q.category.toUpperCase();$('#gamePrompt').textContent=q.prompt;$('#gameProgress').textContent=`Question ${answerIndex+1} of ${game.questions.length}`;$('#gameOptions').innerHTML=q.options.map((o,i)=>`<button data-answer="${i}"><b>${'ABCD'[i]}</b>${o}</button>`).join('');document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>pick(Number(b.dataset.answer)))}
async function pick(a){answers.push(a);answerIndex++;if(answerIndex<game.questions.length)return showQuestion();try{const r=await api(`/api/games/${game.game.id}/submit`,{method:'POST',body:JSON.stringify({answers})});close('game');$('#resultTitle').textContent=r.result==='win'?'You take the round!':r.result==='draw'?'It is a draw.':'A close one.';$('#resultText').textContent=`You scored ${r.score}/${game.questions.length}. ${r.opponentName} scored ${r.opponentScore}/${game.questions.length}.`;open('result');member((await api('/api/me')).user)}catch(x){toast(x.message)}}
$('#playButton').onclick=start;document.querySelectorAll('.game-tile').forEach(b=>b.onclick=start);$('#signOut').onclick=()=>{localStorage.removeItem('jua_token');$('#member').hidden=true;$('#bottomNav').hidden=true;$('#bottomNav').style.display='none';$('#landing').hidden=false;toast('Signed out.')};restore();
